Program     ::= Start Block End

Block       ::= '{' ( Apply | Atom )* '}'

Apply       ::= '(' ( Atom | Apply )+ ')'

Atom        ::= List | Integer | Float | String | Boolean | Void | Identifier | Block

List        ::= '[' ( Atom )* ']'

Integer     ::= [ '-' ] ( Digit )+

Float       ::= [ '-' ] ( Digit )+ '.' ( Digit )+

Digit       ::= '0-9'+

String      ::= '"' [.]* '"'

Boolean     ::= 'true' | 'false'

Void        ::= 'void'

Identifier  ::= [.]+