Program     ::= Start Block End

Block       ::= '{' ( Block | Statement )* '}'

Statement   ::= ( Apply | Define )+

Apply       ::= '(' Identifier ( Atom )* ')'

Define      ::= '(' 'define' Identifier List? Block ')'

Atom        ::= List | Integer | Float| String | Identifier

List        ::= '[' ( Atom )* ']'

Integer     ::= [ '-' ] ( Digit )+

Float       ::= [ '-' ] ( Digit )+ '.' ( Digit )+

Digit       ::= '0-9'+

String      ::= '"' [.]* '"'

Identifier  ::= [.]+