// this is original grammar as used on site to generate diagram
// copy of this in README has semicolons at end of each line to make syntax highlighter happy

Program     ::= Start Scope End

Scope       ::= '{' ( Statement )* '}'

Statement   ::= '(' Identifier ( Atom ) ')'

Atom        ::= List | Integer | Float| String | Identifier | Scope

List        ::= '(' ( Atom )* ')'

Integer     ::= [ '-' ] ( Digit )+

Float       ::= [ '-' ] ( Digit )+ '.' ( Digit )+

String      ::= '"' .* '"'

Identifier  ::= .*

Digit       ::= ( '0-9' )+